### ISSUE TITLE
Move docker images to nanozoo

### ISSUE THREAD

**Issue by lmfaber** [hoelzer-lab/treat#10]
@hoelzer I am currently using these Dockerfiles for the processes Detonate, Ex90N50 and Heatmap. Can you move them to the nanozoo repository and ping me, so I can update the config files?
[Dockerfiles.zip](https://github.com/hoelzer-lab/treat/files/3956724/Dockerfiles.zip)

**Comment by hoelzer** [comment]
@lmfaber I added your 4 Dockerfiles to the nanozoo repository:

nanozoo/ex90n50:2.8.5--69827d7
nanozoo/treat_heatmap:3.1.2--9ed4839
nanozoo/detonate:1.11--1211be0
nanozoo/rsem:1.3.2--21328de

Some are currently building, but seems to work.

**Comment by lmfaber** [comment]
@hoelzer: I changed the repositories. The default setting with docker containers should run on any system now.
