### ISSUE TITLE
rnaQUAST docker

### ISSUE THREAD

**Issue by hoelzer** [hoelzer-lab/treat#2]
I build a new rnaQUAST docker. Please test when you implement the rnaQUAST module. 

This is the current tag:

nanozoo/rnaquast:1.5.2--0ecea11

At least
````
docker run --rm -it nanozoo/rnaquast:latest rnaQUAST.py --help
````
works for me.

**Comment by hoelzer** [comment]
@lmfaber does this docker work?

**Comment by lmfaber** [comment]
Yes, it's working for me so far. A first run with the test data was successful. I didn't test it thoroughly, so there may still be a few undetected issues.

**Comment by hoelzer** [comment]
ok, great. so I will close this issue for now. We can reopen it if something is not working.
