### ISSUE TITLE
Heatmap

### ISSUE THREAD

**Issue by lmfaber** [hoelzer-lab/treat#6]
The script is from my Snakemake pipeline and contains a few Snakemake specific commands which need to be deleted. We would also need to do some minor changes so it will work with this pipeline.

I created a branch for this: https://github.com/hoelzer-lab/treat/tree/heatmap

Dependencies for the script:
```
pandas
numpy
seaborn
matplotlib
```

**Comment by hoelzer** [comment]
hm, maybe it makes sense to simply build a dockerfile for your script to install the dependencies via conda?

**Comment by lmfaber** [comment]
Can be closed with pull request #9.
